project_id = "kgtqnjhmwsvswhrczqaf"

[functions.reset-trial]
verify_jwt = false

[functions.set-user-role]
verify_jwt = false

[functions.create-user-profile]
verify_jwt = false

[functions.create-default-data]
verify_jwt = false

[functions.setup-server-apps]
verify_jwt = false

[functions.check-instance-blocks]
verify_jwt = false
